name: WorldFeatures
version: 0.0.1
main: de.hglabor.worldfeatures.WorldFeatures
api-version: 1.16
depend: ["LuckPerms", "spigot-language-kotlin", "FastAsyncWorldEdit", "ProtocolLib"]
commands:
  feature:
    permission: hglabor.managefeatures
  wiki:
  color:
  rules:
    aliases:
      - report
  spawnentity: